export const createRegistrationAndSpecsSection = () => ({
   country_id: null,
   vin: null,
   state_number: null,
   brand_id: null,
   model_id: null,
   generation_id: null,
   modification_id: null,
   equipment_id: null,
   year_id: null,
   car_body_type_id: null,
   count_doors: null,
   transmission_id: null,
   engine_type_id: null,
   engine_volume: null,
   power_range: null,
   drive_id: null,
   handlebar_id: null,
   mileage: null,
   count_owners: null,
   state_id: null,
   pts_id: null
})

export const createMaintenanceSection = () => ({
   is_service_book: null,
   is_serviced_dealer: null,
   is_under_warranty: null
})

export const createOptionsIdsSection = () => ({
   power_steering_id: null,
   salon_id: null,
   electric_windows_id: null,
   audio_systems_id: null,
   tires_wheels_id: null,
   climate_management_id: null,
   headlight_id: null
})

export const createOptionsFlagsSection = () => ({
   is_front_seats: null,
   is_rear_seats: null,
   is_mirrors: null,
   is_rear_window: null,
   is_steering_wheel: null,
   is_steering_wheel_control: null,
   is_front_seats_drives: null,
   is_rear_seats_drives: null,
   is_mirrors_drives: null,
   is_steering_column_drives: null,
   is_folding_mirrors_drives: null,
   is_front_seats_setting: null,
   is_rear_seats_setting: null,
   is_mirrors_setting: null,
   is_steering_column_setting: null,
   is_blind_spot_monitoring: null,
   is_automatic_parking: null,
   is_rain_sensor: null,
   is_light_sensor: null,
   is_rear_parking_sensor: null,
   is_front_parking_sensor: null,
   is_rear_view_camera: null,
   is_cruise_control: null,
   is_onboard_computer: null,
   is_alarm_system: null,
   is_central_lock: null,
   is_immobilizer: null,
   is_satellite: null,
   is_frontal_airbags: null,
   is_knee_high_airbags: null,
   is_curtains_airbags: null,
   is_side_front_airbags: null,
   is_side_rear_airbags: null,
   is_anti_lock_brakes: null,
   is_anti_slip: null,
   is_exchange_rate_stability: null,
   is_distrib_braking_forces: null,
   is_emergency_braking: null,
   is_differential_block: null,
   is_pedestrian_detection: null,
   is_CD_DVD_Bluray: null,
   is_AUX: null,
   is_MP3: null,
   is_Bluetooth: null,
   is_Radio: null,
   is_TV: null,
   is_Video: null,
   is_USB: null,
   is_GPS_navigator: null,
   is_subwoofer: null,
   is_antifog: null,
   is_washers: null,
   is_adaptive_lighting: null,
   is_athermal_glazing: null,
   is_leather_wheel: null,
   is_hatch: null,
   is_winter_included: null,
   is_wheel_control: null
})
