export const createPassengerTiresSection = () => ({
   tires_condition_id: null,
   tires_count: null,
   tires_brand_id: null,
   tires_manufacturer: null,
   tires_model_id: null,
   tires_season_id: null,
   tires_year_id: null,
   tires_width_id: null,
   tires_height_id: null,
   tires_diameter_id: null,
   tires_staggered_set_id: null,
   tires_rear_width_id: null,
   tires_rear_height_id: null,
   tires_rear_diameter_id: null,
   tires_load_index_id: null,
   tires_speed_index_id: null,
   tires_run_flat_id: null,
   tires_tread_depth_id: null,
   tires_bulges_count_id: null,
   tires_side_repair_count_id: null,
   tires_defect_none: null,
   tires_defect_tread_delamination: null,
   tires_defect_uneven_wear: null,
   tires_defect_cracks: null,
   tires_defect_driven_flat: null
})

export const createPassengerDisksSection = () => ({
   disks_condition_id: null,
   disks_count: null,
   disks_brand_id: null,
   disks_manufacturer: null,
   disks_model_id: null,
   disks_year_id: null,
   disks_rim_diameter_id: null,
   disks_hole_count_id: null,
   disks_hole_pattern_diameter_id: null,
   disks_type_id: null,
   disks_dia_id: null,
   disks_et_id: null,
   disks_rim_width_id: null,
   disks_repair_status_id: null,
   disks_straightened_count_id: null,
   disks_welded_count_id: null,
   disks_cracks_count_id: null,
   disks_geometry_changes_count_id: null,
   disks_paint_type_id: null,
   disks_center_caps_id: null,
   disks_pressure_sensors_id: null,
   disks_defect_none: null,
   disks_defect_scratches: null,
   disks_defect_chips: null,
   disks_defect_coating_delamination: null,
   disks_defect_corrosion_rust: null
})

export const createMotoTiresSection = () => ({
   moto_tires_condition_id: null,
   moto_tires_brand_id: null,
   moto_tires_year_id: null,
   moto_tires_width_id: null,
   moto_tires_height_id: null,
   moto_tires_diameter_id: null,
   moto_tires_count_id: null,
   moto_tires_axle_id: null
})

export const createFullWheelsSection = () => ({
   full_wheels_condition_id: null,
   full_wheels_count: null,
   full_wheels_brand_id: null,
   full_wheels_manufacturer: null,
   full_wheels_model_id: null,
   full_wheels_staggered_set_id: null,
   full_wheels_front_width_id: null,
   full_wheels_front_height_id: null,
   full_wheels_front_diameter_id: null,
   full_wheels_rear_width_id: null,
   full_wheels_rear_height_id: null,
   full_wheels_rear_diameter_id: null,
   full_wheels_load_index_id: null,
   full_wheels_speed_index_id: null,
   full_wheels_season_id: null,
   full_wheels_run_flat_id: null,
   full_wheels_tread_depth_id: null,
   full_wheels_year_id: null,
   full_wheels_disk_rim_diameter_id: null,
   full_wheels_disk_hole_count_id: null,
   full_wheels_disk_hole_pattern_diameter_id: null,
   full_wheels_disk_type_id: null,
   full_wheels_disk_dia_id: null,
   full_wheels_disk_et_id: null,
   full_wheels_disk_rim_width_id: null
})

export const createMotorOilSection = () => ({
   motor_oil_condition_id: null,
   motor_oil_brand_id: null,
   motor_oil_sae_id: null,
   motor_oil_volume_id: null,
   motor_oil_acea_id: null,
   motor_oil_api_id: null,
   motor_oil_oem_id: null,
   motor_oil_article: null,
   motor_oil_article_id: null
})
